#!/bin/bash

# Specify the range of values for n
start=1
end=18

# Loop through the range and create files
for ((n=$start; n<=$end; n++)); do
    filename="${n}-main.py"
    touch "$filename"
done

echo "Files created: ${start}-main.py to ${end}-main.py"

